#!/usr/bin/env sh

vcpkg install

export ZIGSDL='./deps/SDL.zig'
export ZIGPATCHFILEPATH="$ZIGSDL/src/wrapper/sdl.zig"

if [ ! -e "$ZIGSDL" ]; then
  mkdir -p ./deps
  cd ./deps
  git clone https://github.com/MasterQ32/SDL.zig.git
  cd ..

  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' -e 's/pub const c = @import("sdl-native");/\/\/ zig-game hack...\n\/\/ pub const c = @import("sdl-native");\npub const c = @cImport({\n    @cInclude("SDL.h");\n    @cInclude("SDL.h_ttf");\n});/g' $ZIGPATCHFILEPATH
  else
    sed -i -e 's/pub const c = @import("sdl-native");/\/\/ zig-game hack...\n\/\/ pub const c = @import("sdl-native");\npub const c = @cImport({\n    @cInclude("SDL.h");\n    @cInclude("SDL_ttf.h");\n});/g' $ZIGPATCHFILEPATH
  fi
  echo patched $ZIGPATCHFILEPATH
else
  echo "$ZIGSDL exists, not patching $ZIGPATCHFILEPATH" 
fi
