#!/usr/bin/env sh

mkdir -p ./3rdparty
cd ./3rdparty

export ZIGSDL='SDL.zig'
rm -rf "$ZIGSDL"
curl -L "https://github.com/MasterQ32/$ZIGSDL/archive/refs/heads/master.zip" -o "$ZIGSDL.zip"
unzip -x "$ZIGSDL.zip"
mv "$ZIGSDL-master" "$ZIGSDL"
rm -rf "$ZIGSDL.zip"

# Why-oh-why could they not just have stuck to one naming convention...
export SDLVER='2.26.5'
export CSDLVER="SDL2-$SDLVER"
export CSDLDEVVC="SDL2-devel-$SDLVER-VC"
export CSDLVC="SDL2-$SDLVER-VC"
rm -rf "$CSDLDEVVC"
curl -L "https://github.com/libsdl-org/SDL/releases/download/release-2.26.5/$CSDLDEVVC.zip" -o "$CSDLVER.zip"
unzip -x "$CSDLVER.zip"
mv "$CSDLVER" "$CSDLDEVVC"
rm "$CSDLVER.zip"

# hack patch for zig sdl
export ZIGPATCHFILEPATH="./$ZIGSDL/src/wrapper/sdl.zig"
if [[ "$OSTYPE" == "darwin"* ]]; then
  sed -i '' -e 's/pub const c = @import("sdl-native");/\/\/ zig-game hack...\n\/\/ pub const c = @import("sdl-native");\npub const c = @cImport({\n    @cInclude("SDL.h");\n});/g' $ZIGPATCHFILEPATH
else
  sed -i -e 's/pub const c = @import("sdl-native");/\/\/ zig-game hack...\n\/\/ pub const c = @import("sdl-native");\npub const c = @cImport({\n    @cInclude("SDL.h");\n});/g' $ZIGPATCHFILEPATH
fi
echo patched $ZIGPATCHFILEPATH
