#!/usr/bin/env sh

vcpkg install

export ZIGSDL='./deps/SDL.zig'
export ZIGPATCHFILEPATH="$ZIGSDL/src/wrapper/sdl.zig"

if [ ! -e "$ZIGSDL" ]; then
  mkdir -p ./deps
  cd ./deps
  git clone https://github.com/MasterQ32/SDL.zig.git
  cd ..

export SUBST_STR='s|pub const c = @import("sdl-native");|// zig-game hack...\n// pub const c = @import("sdl-native");\npub const c = @cImport({\n    @cInclude("SDL2/SDL.h");\n    @cInclude("SDL2/SDL_ttf.h");\n});|g'
  if [ "$OSTYPE" == "darwin"* ]; then
    sed -i '' -e "$SUBST_STR" $ZIGPATCHFILEPATH
  else
    sed -i -e "$SUBST_STR" $ZIGPATCHFILEPATH
  fi
  echo patched $ZIGPATCHFILEPATH
else
  echo "$ZIGSDL exists, not patching $ZIGPATCHFILEPATH" 
fi
